#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# The three job names from .github/workflows/ci.yml. GitHub matches a required
# check by its job `name:` EXACTLY, em-dashes and all — so these are copied from
# the workflow, never retyped.
CHECK_BACKEND="backend — test + build"
CHECK_FRONTEND="frontend — typecheck + build"
CHECK_PROMOTION="branch promotion order"

HAVE_GH="no"
REPO=""
ENFORCE_ADMINS="false"

banner "Branch protection · staging + main"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: has CI reported yet?"
say "GitHub only offers a check in the required-checks picker once that check"
say "has reported on the repo recently. So the pipeline has to have run once."
printf '\n'

REPO=$(git config --get remote.origin.url 2>/dev/null \
  | sed -E 's#^.*github\.com[:/]##; s#\.git$##') || true
if [[ -n "$REPO" ]]; then
  say "Repo detected as ${BOLD}${REPO}${RESET}"
  confirm "Is that right?" || REPO=""
fi

# Every later stage builds a URL and an API path out of this, so a bad value
# here fails four stages later as a confusing 404. Settle it now.
while [[ ! "$REPO" =~ ^[A-Za-z0-9._-]+/[A-Za-z0-9._-]+$ ]]; do
  [[ -n "$REPO" ]] && warn "\"$REPO\" is not owner/repo."
  ask REPO "Enter owner/repo (e.g. AdiGo112/Wchess):"
done
printf '\n'

open_url "https://github.com/${REPO}/actions"
step "Look for a run of the 'CI' workflow on the dev branch."
step "It should show two jobs: '${CHECK_BACKEND}' and '${CHECK_FRONTEND}'."
printf '\n'
warn "'${CHECK_PROMOTION}' will NOT be there yet."
note "That job is PR-only, so a push to dev never triggers it. You can still"
note "require it — type the name by hand rather than picking it from the list —"
note "or come back and add it after your first PR."
printf '\n'
pause "Seen the run? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "GitHub CLI: authenticate (or skip)"
say "With gh authenticated, this wizard applies the settings directly."
say "Without it, it walks you through the web UI instead. Same end state."
printf '\n'

if ! command -v gh >/dev/null 2>&1; then
  warn "gh is not installed — using the web UI path."
  note "If you would rather script it next time: https://cli.github.com"
  SKIPPED+=("install gh, to make branch protection scriptable next time")
elif gh auth status >/dev/null 2>&1; then
  say "gh is already authenticated."
  HAVE_GH="yes"
else
  warn "gh is installed but not logged in."
  if confirm "Run 'gh auth login' now? (interactive, opens a browser)"; then
    gh auth login || true
    if gh auth status >/dev/null 2>&1; then
      say "Authenticated."
      HAVE_GH="yes"
    else
      warn "Still not authenticated — falling back to the web UI path."
    fi
  else
    note "Fine — web UI path it is."
  fi
fi
printf '\n'

if [[ "$HAVE_GH" == "yes" ]]; then
  say "One decision before anything is applied:"
  printf '\n'
  step "Enforce these rules on admins too?"
  note "You are the only developer. Enforced-on-admins means a broken pipeline"
  note "can lock YOU out of your own main branch until it goes green. Left off,"
  note "the rules stop an absent-minded merge but you can always override."
  printf '\n'
  if confirm "Enforce on admins as well? (default: no)"; then
    ENFORCE_ADMINS="true"
  fi
fi
pause

# _protect BRANCH — applies (gh) or explains (web UI) protection for one branch.
_protect() {
  local branch="$1" payload
  if [[ "$HAVE_GH" == "yes" ]]; then
    payload=$(mktemp)
    cat > "$payload" <<JSON
{
  "required_status_checks": {
    "strict": true,
    "contexts": ["${CHECK_BACKEND}", "${CHECK_FRONTEND}", "${CHECK_PROMOTION}"]
  },
  "enforce_admins": ${ENFORCE_ADMINS},
  "required_pull_request_reviews": { "required_approving_review_count": 0 },
  "restrictions": null,
  "allow_force_pushes": false,
  "allow_deletions": false
}
JSON
    say "About to PUT this to ${BOLD}${branch}${RESET}:"
    printf '\n'
    sed 's/^/      /' "$payload"
    printf '\n'
    note "required_approving_review_count is 0 on purpose: a PR is still"
    note "required, but a solo developer forced to approve their own PR could"
    note "never merge anything."
    printf '\n'
    if confirm "Apply to ${branch}?"; then
      if gh api -X PUT "repos/${REPO}/branches/${branch}/protection" \
           -H "Accept: application/vnd.github+json" \
           --input "$payload" >/dev/null 2>&1; then
        printf '  %s✓ protected%s %s\n' "$GREEN" "$RESET" "$branch"
      else
        warn "the API call failed for ${branch}."
        note "Most likely causes, in order:"
        note "  - private repo on a plan without classic branch protection;"
        note "    use Rulesets instead (Settings -> Rules -> Rulesets)"
        note "  - token lacks admin rights: gh auth refresh -s repo,admin:org"
        note "  - the branch '${branch}' does not exist on the remote"
        SKIPPED+=("branch protection on ${branch} — API call failed")
      fi
    else
      note "Skipped ${branch}."
      SKIPPED+=("branch protection on ${branch} — you declined")
    fi
    rm -f "$payload"
  else
    open_url "https://github.com/${REPO}/settings/branches"
    step "Add a rule for ${BOLD}${branch}${RESET}. The button is 'Add branch"
    step "  ruleset', or 'Add classic branch protection rule' — either works."
    step "Branch name pattern: ${branch}"
    printf '\n'
    say "Turn on:"
    step "Require a pull request before merging"
    note "    set required approvals to 0 — you are the only reviewer"
    step "Require status checks to pass before merging"
    step "Require branches to be up to date before merging"
    printf '\n'
    say "Then add these three checks by name:"
    note "    ${CHECK_BACKEND}"
    note "    ${CHECK_FRONTEND}"
    note "    ${CHECK_PROMOTION}"
    printf '\n'
    warn "GitHub rearranges this page often, so trust the setting NAMES above"
    warn "rather than any exact click path."
    printf '\n'
    pause "Done with ${branch}? Press Enter."
  fi
}

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Protect: staging"
say "staging accepts PRs from dev only. The promotion job is what enforces"
say "that, which is exactly why it has to be required rather than suggested."
printf '\n'
_protect staging

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Protect: main"
say "main accepts staging, or a hotfix/* branch when production is broken and"
say "staging is not clean. Same three checks."
printf '\n'
_protect main

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify"
if [[ "$HAVE_GH" == "yes" ]]; then
  for b in staging main; do
    printf '\n  %s%s%s\n' "$BOLD" "$b" "$RESET"
    gh api "repos/${REPO}/branches/${b}/protection" --jq '
      "    PR required: \(.required_pull_request_reviews != null)
    up to date:  \(.required_status_checks.strict)
    checks:      \(.required_status_checks.contexts | join(" · "))
    admins:      \(.enforce_admins.enabled)"' 2>/dev/null \
      || warn "could not read protection for ${b} (not set, or no admin rights)"
  done
else
  open_url "https://github.com/${REPO}/settings/branches"
  say "Both branches should now be listed with a rule against them."
fi

printf '\n'
say "The real test — open a PR that should NOT be allowed:"
note "    git push origin dev:refs/heads/tmp-promotion-check"
note "    gh pr create --base main --head tmp-promotion-check --fill"
note "It must fail 'branch promotion order'. Delete the branch afterwards:"
note "    git push origin --delete tmp-promotion-check"
printf '\n'
note "These settings are written up in docs/infrastructure/ci-cd.md §5."
pause

finish
